CREATE TABLE `heroes3_maps` (
	`idm` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`mapfile` VARCHAR(128) NULL DEFAULT NULL,
	`mapdir` VARCHAR(128) NULL DEFAULT NULL,
	`mapname` VARCHAR(128) NULL DEFAULT NULL,
	`mapdesc` TEXT NULL,
	`version` VARCHAR(8) NULL DEFAULT NULL,
	`size` INT(10) UNSIGNED NULL DEFAULT NULL,
	`sizename` VARCHAR(8) NULL DEFAULT NULL,
	`levels` INT(10) UNSIGNED NULL DEFAULT NULL,
	`diff` VARCHAR(50) NULL DEFAULT NULL,
	`playersnum` TINYINT(4) NULL DEFAULT NULL,
	`playhuman` TINYINT(4) NULL DEFAULT NULL,
	`playai` TINYINT(4) NULL DEFAULT NULL,
	`teamnum` TINYINT(4) NULL DEFAULT NULL,
	`victory` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`loss` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`added` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`filecreate` TIMESTAMP NULL DEFAULT NULL,
	`filechanged` TIMESTAMP NULL DEFAULT NULL,
	`filesizeC` INT(10) UNSIGNED NULL DEFAULT NULL,
	`filesizeU` INT(10) UNSIGNED NULL DEFAULT NULL,
	`mapimage` VARCHAR(128) NULL DEFAULT NULL,
	PRIMARY KEY (`idm`)
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
