CREATE TABLE `heroes3_maps` (
	`idm` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`heroes` TINYINT(3) UNSIGNED NOT NULL DEFAULT '3' COMMENT 'heroes series',
	`campaign` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '0=map; 1=campaign',
	`id_campaign` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'id of campaign where map belongs',
	`mapfile` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`mapdir` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`mapname` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`author` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`language` VARCHAR(16) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`mapdesc` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`version` VARCHAR(8) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`subversion` TINYINT(3) UNSIGNED NULL DEFAULT '0',
	`size` INT(10) UNSIGNED NULL DEFAULT NULL,
	`sizename` VARCHAR(3) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`levels` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`diff` TINYINT(4) NULL DEFAULT NULL,
	`diffname` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`playersnum` TINYINT(4) NULL DEFAULT NULL,
	`playhuman` TINYINT(4) NULL DEFAULT NULL,
	`playai` TINYINT(4) NULL DEFAULT NULL,
	`teamnum` TINYINT(4) NULL DEFAULT NULL,
	`victory` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`loss` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`added` TIMESTAMP NULL DEFAULT current_timestamp(),
	`filecreate` TIMESTAMP NULL DEFAULT NULL,
	`filechanged` TIMESTAMP NULL DEFAULT NULL,
	`filesizeC` INT(10) UNSIGNED NULL DEFAULT NULL,
	`filesizeU` INT(10) UNSIGNED NULL DEFAULT NULL,
	`mapimage` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`md5` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`idm`) USING BTREE,
	INDEX `mapname` (`mapname`) USING BTREE,
	INDEX `version` (`version`) USING BTREE,
	INDEX `size` (`size`) USING BTREE,
	INDEX `playersnum` (`playersnum`) USING BTREE,
	INDEX `victory` (`victory`) USING BTREE,
	INDEX `loss` (`loss`) USING BTREE,
	INDEX `playhuman` (`playhuman`) USING BTREE,
	INDEX `campaign` (`campaign`) USING BTREE,
	INDEX `heroes` (`heroes`) USING BTREE,
	INDEX `mapfile` (`mapfile`) USING BTREE,
	INDEX `diff` (`diff`) USING BTREE,
	INDEX `levels` (`levels`) USING BTREE,
	INDEX `md5` (`md5`) USING BTREE,
	INDEX `id_campaign` (`id_campaign`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
