CREATE TABLE `heroes3_maps` (
	`idm` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`heroes` TINYINT(3) UNSIGNED NOT NULL DEFAULT '3' COMMENT 'heroes series',
	`campaign` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '0=map; 1=campaign',
	`id_campaign` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'id of campaign where map belongs',
	`mapfile` VARCHAR(128) NULL DEFAULT NULL,
	`mapdir` VARCHAR(128) NULL DEFAULT NULL,
	`mapname` VARCHAR(128) NULL DEFAULT NULL,
	`author` VARCHAR(128) NULL DEFAULT NULL,
	`language` VARCHAR(16) NOT NULL DEFAULT '',
	`mapdesc` MEDIUMTEXT NULL,
	`version` VARCHAR(8) NULL DEFAULT NULL,
	`subversion` TINYINT(3) UNSIGNED NULL DEFAULT '0',
	`size` INT(10) UNSIGNED NULL DEFAULT NULL,
	`sizename` VARCHAR(3) NULL DEFAULT NULL,
	`levels` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`diff` TINYINT(4) NULL DEFAULT NULL,
	`diffname` VARCHAR(50) NULL DEFAULT NULL,
	`playersnum` TINYINT(4) NULL DEFAULT NULL,
	`playhuman` TINYINT(4) NULL DEFAULT NULL,
	`playai` TINYINT(4) NULL DEFAULT NULL,
	`teamnum` TINYINT(4) NULL DEFAULT NULL,
	`victory` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`loss` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`added` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`filecreate` TIMESTAMP NULL DEFAULT NULL,
	`filechanged` TIMESTAMP NULL DEFAULT NULL,
	`filesizeC` INT(10) UNSIGNED NULL DEFAULT NULL,
	`filesizeU` INT(10) UNSIGNED NULL DEFAULT NULL,
	`mapimage` VARCHAR(128) NULL DEFAULT NULL,
	`md5` VARCHAR(32) NULL DEFAULT NULL,
	PRIMARY KEY (`idm`),
	INDEX `mapname` (`mapname`),
	INDEX `version` (`version`),
	INDEX `size` (`size`),
	INDEX `playersnum` (`playersnum`),
	INDEX `victory` (`victory`),
	INDEX `loss` (`loss`),
	INDEX `playhuman` (`playhuman`),
	INDEX `campaign` (`campaign`),
	INDEX `heroes` (`heroes`),
	INDEX `mapfile` (`mapfile`),
	INDEX `diff` (`diff`),
	INDEX `levels` (`levels`)
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
